let products = [
    {
        id: 0,
        itemCode: '92370',
        brand: 'The North Face',
        description: "Dome Short Sleeve T-Shirt",
        features: ["Men's t-shirt", 'Regular fit', 'Comfortable cotton fabric', 'Crew neckline', 'Material: 100% Cotton'],
        price: 18.95,
        image: '92370.jpg',
        inStock: 'Out of Stock',
        qty: 0,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 1,
        itemCode: '13745',
        brand: 'Vans',
        description: "Classic Short Sleeve T-Shirt",
        features: [ 'Mens round neck, short sleeve tee', 'Classic fit', 'Ringspun cotton', 'Printed branding', 'Material: 100% Cotton'],
        price: 19.95,
        image: '13745.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 2,
        itemCode: '146283',
        brand: "O'Neill",
        description: "Brand Short Sleeve T-Shirt",
        features: [ "O'Neill logo detailing", 'Regular fit', 'Crew neckline', 'Printed branding', 'Material: 100% Cotton'],
        price: 11.95,
        image: '146283.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 3,
        itemCode: '294429',
        brand: "Billabong",
        description: "Trademark Short Sleeve T-Shirt",
        features: [ "Mens short sleeve t-shirt", 'Regular fit', 'Crew neckline', 'Billabong trademark branding printed on the chest', 'Material: 100% Cotton'],
        price: 18.25,
        image: '294429.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 4,
        itemCode: '265860',
        brand: "Element",
        description: "Seal Short Sleeve T-Shirt",
        features: [ "Mens short sleeve t-shirt", 'Regular fit', 'Crew neckline', 'Large Element graphic printed on the chest', 'Material: 100% Cotton'],
        price: 24.95,
        image: '265860.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 5,
        itemCode: '265639',
        brand: 'Quiksilver',
        description: "Highline Slab 20 Boardshorts",
        features: ["Trendy men's boardshorts", 'Repreve 4-way stretch fabric', 'Water-repellent finish', 'Key attachment cord in the pocket', 'Draw-string adjustable waist'],
        price: 27.95,
        image: '265639.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Short',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 6,
        itemCode: '266743',
        brand: 'Rip Curl',
        description: "Rapture Layday Boardshorts",
        features: ["Mens boardshorts", '19" out seam length', 'Cinch drawcord on the waist', 'Key attachment cord in the pocket', '2 open entry hand pockets', 'Back pocket with a key loop'],
        price: 27.45,
        image: '266743.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Short',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 7,
        itemCode: '268474',
        brand: 'Billabong',
        description: "73 Stripe Og Boardshorts",
        features: ["Mens boardshorts", '18" length', 'Surf Suede Fabric', 'Split binding', '2 open entry hand pocketMicro repel coating', 'Scallop hem'],
        price: 43.35,
        image: '268474.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Short',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 8,
        itemCode: '266914',
        brand: 'Rip Curl',
        description: 'Seaside 16" Volley Boardshorts',
        features: ["Mens volley swimming shorts", '16" outseam length', 'Fully elasticated waistband feels comfortable and improves the fit', 'External drawcord to adjust and secure the fit', '2 open entry hand pockets and a self draining back patch pocket'],
        price: 25.55,
        image: '266914.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Short',
        category: 'summer',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 9,
        itemCode: '291008',
        brand: 'RVCA',
        description: "RCVA Man Service Jacket",
        features: ["Mens zip up jacket", 'Full length exposed metal zip', 'Duel entry hip pockets', 'Button fastenings on the cuffs', 'Adjustable hem with fabric straps and button fastenings on the back', 'Internal plaid lining '],
        price: 90.85,
        image: '291008.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Jacket',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 10,
        itemCode: '289022',
        brand: 'Rip Curl',
        description: 'Rip Curl Logging Jacket',
        features: ["Mens heavy flannel jacket", 'Soft and thick Sherpa collar', 'Full length exposed metal zip', 'Two patch pockets on the chest', 'Button fastenings on the cuffs', 'Rip Curl patch on the upper left sleeve', 'Relaxed fit in the body'],
        price: 126.95,
        image: '289022.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Jacket',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 11,
        itemCode: '288167',
        brand: 'Banks',
        description: 'Banks Reversible Lumber Jacket',
        features: ["Mens reversible lumbar jacket", 'Wool and polyester blend on one side with a bushed flannel interior', 'Button fastenings on the cuffs', 'Full length exposed zip', 'Fabric Banks label made from recycled polyester', 'Open entry chest pocket on the left hand side and two welted pockets'],
        price: 110.95,
        image: '288167.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Jacket',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 12,
        itemCode: '288802',
        brand: 'DC',
        description: 'DC Missile Padded Jacket',
        features: ["Mens lightweight windbreaker jacket", 'Water resistant coating on the face fabric encourages water to bead off', 'Lightweight synthetic insulation', 'Adjustable hood to close the fit around your face', 'Full length main zip', 'Stretch binding on the cuffs', 'Large DC branding on the left side of the chest'],
        price: 70.95,
        image: '288802.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Jacket',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 13,
        itemCode: '289521',
        brand: 'Quiksilver',
        description: 'Quiksilver Ichaca Cargo Pants',
        features: ["Mens cargo style pants", 'Two large cargo pockets on', 'Two hand pockets', 'Two back pockets', 'Zipped fly with a shank button fastening', 'Small fabric label on the right pocket', 'Material: 100% Cotton'],
        price: 54.45,
        image: '289521.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Pants',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 14,
        itemCode: '128648',
        brand: 'Dickies',
        description: 'Dickies Original 874 Work Chino Pant',
        features: ["Men's chino pants", 'Straight leg', 'Wrinkle-resistant', 'Hand pockets', 'Back pockets', 'Small branding patch near the back pocket', 'Material: 100% Cotton'],
        price: 58.95,
        image: '128648.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Pants',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 15,
        itemCode: '253903',
        brand: 'Globe',
        description: 'Globe Goodstock Chino Pant',
        features: ["Fly and button fastening", 'Straight leg', 'Two front pockets', 'Hand pockets', 'Back pockets', 'Branded buttons', 'Material: 100% Cotton'],
        price: 62.35,
        image: '253903.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Pants',
        category: 'outwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 16,
        itemCode: '290590',
        brand: 'Volcom',
        description: 'Volcom Forzee Crew Sweater',
        features: ["Mens pullover sweater", 'Contrasting stripes on the lower half of the body', 'Crew neckline', 'Volcom fabric patch on the left side of the chest', 'Regular fit in the body', '80% Cotton', '20% Polyester'],
        price: 60.95,
        image: '290590.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Sweater',
        category: 'streetwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 17,
        itemCode: '289604',
        brand: 'Quiksilver',
        description: 'Quiksilver Soul Power Sweater',
        features: ["Mens pullover sweater", 'Mid weight warm polar fleece', 'Quiksilver WarmFlight technology', 'Moisture wicking fabric keeps you dry and comfortable', 'Crew neckline with a ribbed collar', 'Stretch ribbed finish on the hem and cuffs', 'High Altitude patch on the left side of the chest','100% Polyester'],
        price: 71.45,
        image: '289604.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Sweater',
        category: 'streetwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 18,
        itemCode: '316964',
        brand: 'Element',
        description: 'Element Vertical Long Sleeve T-Shirt',
        features: ["Mens long sleeve top", 'Crew neckline', 'Large Element branding printed across the chest', 'Fabric clamp label on the hem', 'Regular fit in the body', '100% Cotton'],
        price: 28.95,
        image: '316964.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Long sleeve',
        category: 'streetwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 19,
        itemCode: '293216',
        brand: 'Protest',
        description: 'Protest Nxg Kilimano Long Sleeve T-Shirt',
        features: ["Mens long sleeve top", 'Crew neckline', 'Large NXG branding printed on the back', 'Small NXG branding printed on the left side of the chest', 'Fabric label on the hem and back of the neck', 'Regular fit in the body', '40% Polyester', '60% Cotton'],
        price: 30.45,
        image: '293216.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Long sleeve',
        category: 'streetwear',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 20,
        itemCode: '264637',
        brand: 'Element',
        description: 'Blazin Short Sleeve T-Shirt',
        features: ["Men's Element Blazin Short Sleeve T-Shirt", 'Signature logo print across the chest', 'Comfortable jersey material', 'Ribbed crew neck', 'Straight cut hemline', 'Regular fit in the body', 'Regular Fit', '100% Cotton'],
        price: 15.99,
        image: '264637.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'sale',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 21,
        itemCode: '265476',
        brand: 'Quiksilver',
        description: 'New Slang Short Sleeve T-Shirt',
        features: ["Short sleeve t-shirt", 'Crew neckline', 'Comfortable jersey material', 'Quiksilver branding printed across the chest', 'Small Quiksilver fabric clamp label on the left sleeve', 'Regular fit in the body', 'Regular Fit', '100% Cotton'],
        price: 15.99,
        image: '265476.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'T-Shirt',
        category: 'sale',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 22,
        itemCode: '264759',
        brand: 'Volcom',
        description: 'Pen Bsc Long Sleeve T-Shirt',
        features: ["Men's long sleeve T-shirt", 'Raglan sleeves', 'Contrast-colour sleeves', 'Small brand logo on left side chest', 'Regular fit in the body', '100% Cotton'],
        price: 24.99,
        image: '264759.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'Long sleeve',
        category: 'sale',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 23,
        itemCode: '265147',
        brand: 'Element',
        description: 'Cornell Classic Pullover Hoody',
        features: ["Men's Element Hoodie", 'Pullover design', 'Attached hood with adjustable drawstrings', 'Front pouch pocket', 'Ribbed cuffs and hem', 'Element logo to left chest', 'Regular fit in the body', '60% Polyester', '40% Cotton'],
        price: 29.99,
        image: '265147.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'outwear',
        category: 'sale',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    },
    {
        id: 24,
        itemCode: '292194',
        brand: 'Element',
        description: 'Dulcey Jacket',
        features: ["Mens lightweight casual outdoor jacket", 'Windproof fabric', 'Tough ripstop lining in the hood and body', 'Full length exposed metal zip', 'Two open entry hand warmer pockets', 'Secure internal pocket', 'Adjustable drawcord on the hood with reinforced metal eyelets', 'Reflective detailing on the hood drawcord increases your visibility in low light', 'Stretch ribbed finish on the hem and cuffs '],
        price: 99.99,
        image: '292194.jpg',
        inStock: 'In Stock',
        qty: 10,
        size: ['Small', 'Medium', 'Large'],
        type: 'jacket',
        category: 'sale',
        orderedSizeSmall: 0,
        orderedSizeMedium: 0,
        orderedSizeLarge: 0
    }
  ];
  
  export { products };
  